CMU_KITCHENS:
  METADATA_FILE: ./annotations/metadata/CMU_Kitchens/tasks.txt
  VIDEOS_PATH: ./videos
  ANNS_PATH: ./annotations
  FRAMES_PATH: ./frames
  VIEW: back
ANNOTATION:
  CATEGORY: Sandwich
DATA_LOADER:
  NUM_WORKERS: 0
  SHUFFLE: False
  CROP_SIZE: 224
  SAMPLING_FPS: 2
  PIN_MEMORY: True
MISC:
  DEBUG_VIZ_PATH: ""
  VERBOSE: True
LOG:
  DIR: .logs
  LEVEL: debug
TCC:
  DATA_PATH: ./logs
  TRAIN_EPOCHS: 10000
  KMEANS_NUM_CLUSTERS: 30
  BATCH_SIZE: 2
  NUM_FRAMES: 32
  NUM_CONTEXT_STEPS: 2
  CONTEXT_STRIDE: 15
  LSTM: False
  BILSTM: False
LAV:
  USE_CIDM: True
  CONTRIB_PERCENT: 0.1
